Add director
DnbDnbMda/java-filmorate pull request #11
Opened 2023-06-21 13:34 UTC by EsiaBelos

Функционал режиссеры

2023-06-21 14:27 UTC, DnbDnbMda commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    private final MpaStorage mpaStorage; // похоже это поле не используется, предлагаю удалить
Учту при подготовке к финальному ревью

2023-06-21 14:40 UTC, DnbDnbMda commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private final GenreStorage genreStorage; //убрать поля с другими хранилищами?
При подготовке к финальному ревью уберу

2023-06-21 14:41 UTC, DnbDnbMda commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public FilmDbStorage(NamedParameterJdbcTemplate namedParameterJdbcTemplate, JdbcTemplate jdbcTemplate, GenreStorage genreStorage, FilmGenreDbStorage filmGenreDbStorage, MpaDbStorage mpaDbStorage)
Надо не забыть заменить на аннотацию ломбок

2023-06-21 14:47 UTC, DnbDnbMda commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        //а можно так записать метод
Согласен. Учту перед подготовкой к финальному ревью

2023-06-21 14:50 UTC, DnbDnbMda commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +//                .build();
Закомментированный код лучше убрать, ревьювер не пропустит 100%

2023-06-21 14:55 UTC, DnbDnbMda reviewed
Вынес ряд моментов для финального анализа с моей стороны.
Предлагаю только убрать закомментированный код.

2023-06-21 15:26 UTC, ibez51 requested changes
Хорошо сделано. 
Есть несколько моментов к обсуждению, и мне понравилась встроенная фича с автоматической очисткой данных перед каждым тестом!

2023-06-21 15:26 UTC, ibez51 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +@Slf4j
Логирование в этом методе не используется, поэтому аннотацию можно убрать.

2023-06-21 15:26 UTC, ibez51 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +//    }
Если код больше не нужен, его стоит удалить.

2023-06-21 15:26 UTC, ibez51 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +//                .build();
Давай использовать этот вариант? Он выглядит лаконично.

2023-06-21 15:26 UTC, ibez51 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private final GenreStorage genreStorage; //убрать поля с другими хранилищами?
Спорный вопрос. У нас задача добавить новые возможности, а не переписать существующий функционал. Я бы оставил.

2023-06-21 15:26 UTC, ibez51 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    private final MpaStorage mpaStorage; // похоже это поле не используется, предлагаю удалить
Согласен, давай.

2023-06-21 19:24 UTC, EsiaBelos commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private final GenreStorage genreStorage; //убрать поля с другими хранилищами?
Поля не используются, идеа подсвечивает их серым, поэтому я предложила удалить

2023-06-21 19:42 UTC, DnbDnbMda approved these changes
Всё отлично. Спасибо!

2023-06-22 06:09 UTC, ibez51 approved these changes
Всё хорошо, можно мерджить.

2023-06-22 08:09 UTC, merged