Add recommendations
DnbDnbMda/java-filmorate pull request #19
Opened 2023-06-23 03:05 UTC by Sardiand

Сделал систему рекомендаций.

2023-06-23 16:35 UTC, pursecookie requested changes

2023-06-23 16:35 UTC, pursecookie commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        return filmServiceImpl.getRecommendation(userId);
Насколько мне известно, сервисы друг о друге не должны знать, но, например, тут можно сослаться на хранилище фильмов.

2023-06-23 16:35 UTC, pursecookie commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getRecommendation(id);
Можем ли мы здесь вызвать метод filmService.getRecommendation(id)? Потому что мне кажется, что сервис не должен потом ссылаться на другой сервис.

Интересный момент. URL вроде идет по пути /users/, но работа по сути ведется с фильмами.

2023-06-23 17:54 UTC, Sardiand commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getRecommendation(id);
Да, я не хотел тащить все  несколько Storage классов для UserService, но ты права, делать импорт FilmService тоже не камильфо.

2023-06-24 08:35 UTC, pursecookie approved these changes

2023-06-25 09:10 UTC, EsiaBelos approved these changes

2023-06-26 05:44 UTC, merged