реализован функционал add-most-popular
DnbDnbMda/java-filmorate pull request #21
Opened 2023-06-23 11:04 UTC by OlegS19

2023-06-23 16:24 UTC, pursecookie requested changes

2023-06-23 16:24 UTC, pursecookie commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                "WHERE 1 = 1 ";
Можешь, пожалуйста, объяснить, что значит "WHERE 1 = 1"?

2023-06-23 16:24 UTC, pursecookie commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        List<Film> popularFilms = filmDbStorage.getMostPopularFilms(1, null,null);
Наверное, нужно дополнительно протестировать введение новой функциональности. Данный тест не тестирует фильтрацию по жанру, по году и одновременно по жанру и по году. См. примеры тестов в закрытом PR #16

2023-06-23 16:25 UTC, pursecookie commented
Привет! В целом, все рабочее. Есть одно замечание по тестам.

2023-06-23 19:02 UTC, DnbDnbMda reviewed
На мой взгляд комментарии Ксении объективны, готов совместно проработать доработки.

2023-06-24 12:18 UTC, OlegS19 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                "WHERE 1 = 1 ";
where 1 = 1 в БД это то же самое, что в java if (true), то есть всегда истина

2023-06-26 09:39 UTC, OlegS19 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        List<Film> popularFilms = filmDbStorage.getMostPopularFilms(1, null,null);
Тест добавлен

2023-06-26 10:07 UTC, pursecookie commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        List<Film> popularFilms = filmDbStorage.getMostPopularFilms(1, null,null);
> Тест добавлен

Я думала ты дополнишь уже существующий тест testGetMostPopularFilms() :)
Давай может быть тогда твой тест переименуем, чтобы путаницы в них не было? Например, testGetMostPopularFilmsByGenreAndYear(). А то у нас тогда получается два теста с идентичными названиями, и, если не залезть разбираться в код теста, сразу не понять, в чем разница.

2023-06-26 10:27 UTC, Sardiand approved these changes
В целом норм, переименуй и готово.

2023-06-26 10:27 UTC, Sardiand commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        assertNotNull(findByYear.stream().filter(film -> film.getId() == 2).findFirst().orElse(null));
Тут тесты не очень информативные, я бы ещё посмотрел, не подтянутся ли фильмы разных жанров, но одного года при сортировке по жанру и году и наоборот. Но это так, в целом пойдет.

2023-06-26 10:37 UTC, OlegS19 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        List<Film> popularFilms = filmDbStorage.getMostPopularFilms(1, null,null);
Тест переименован

2023-06-26 10:42 UTC, pursecookie approved these changes

2023-06-26 10:48 UTC, merged